version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://vijay:14Td2934%40@13.234.75.21:3306/fastapi_auth  # Use pymysql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fastapi-network

 
